on:
  push:
    branches:
      - main
    paths:
      - ".wiki/**"
  workflow_dispatch:

jobs:
  push-docs-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install markdown lib for Python
        run: |
          python -m pip install --upgrade pip
          pip install markdown
      - name: Debug 1
        run: ls
      - name: Run sidebar generator
        run: |
          python3 ./wiki/generate_sidebar.py
      - name: Debug 2
        run: ls
      - name: Push docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: .wiki/docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
